### ISSUE TITLE
What is the license of this library/repo?

### ISSUE THREAD

**Issue by saidinesh5** [wxggg/libevent-cpp#1]
I would like try to use this library in one of the projects I am working on. So is this library allowed to be used in commercial settings?

**Comment by wxggg** [comment]
The library is free to use, but i'd like to say there might be some bugs when dealing with high concurrency for a long time., the code may corrupt. Anyway, you can use it free.

**Comment by saidinesh5** [comment]
Hi, Thanks for your response. I patched the library a little more for our usecase (to use the same event loop for both timers and http server/client), but i encountered some additional bugs/leaks/crashes - especially when stopping the event loop from within an http callback, and i didn't have enough time to debug this more.

Fortunately i found this library in the last minute: https://github.com/yedf/handy , so I used this to meet my deadline. That library is quite a bit similar to your libevent-cpp, i was kind of curious if you were behind it!

Just a couple of notes from me while patching this library: I think there might be some performance bonuses awaiting us, if we use shared_ptr vs. unique_ptr based on the kind of event loop we are choosing (multithreaded vs. singlethreaded). Additionally, it may be worth it to use external libraries like libyaurel: https://github.com/jacketizer/libyuarel/tree/ffdd690698077b29151ab13ce8ac1b2b2379068c for parsing http requests.

**Comment by wxggg** [comment]
Thanks for your propose, I did this project mainly for learning, so there might be some bugs. And the idea is mainly based on the libevent-1.4. I will think carefully about what you said.  But i have some other works to do these months, so right now i might have no time to continue to improve this project, but i will consider it later.
